# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: Netresearch DTT GmbH

extends: default
rules:
  line-length: {max: 160}
  truthy: {allowed-values: ['true', 'false', 'on']}
  document-start: disable
