"""The strikethrough grammar, checked against recorded Jira output.

Two fixtures, both recorded from a live Jira Server 9.12 wiki renderer:

* ``strikethrough_oracle.json`` - 209 curated cases WITH their rendered HTML.
  These are the ones to read to understand the rule; the span-body assertions
  run against them.
* ``strikethrough_corpus.json`` - 5732 cases generated by
  ``scripts/generate-strikethrough-corpus.py``, recorded as a struck/not-struck
  flag. This is what turns "I thought of the cases" into "the suite found them".

The contract is deliberately asymmetric, and that is the point:

* **No false negatives.** Every ``<del>`` the renderer produced must be
  covered by a predicted span - except a pinned list of shapes that glue a URL
  or link macro directly to another one, which prose does not do.
* **False positives are allowed and pinned.** Predicting a span Jira would not
  draw costs one redundant ``\\-``, which prints as a plain hyphen. Missing one
  mangles the text. The model is a superset on purpose, and the exact set of
  over-predictions is pinned so it cannot grow unnoticed.

Two hand-derived versions of this rule were wrong before this suite existed.
The first claimed ``journalctl -b -p crit`` was a matched pair (it is not). The
second was pinned to 168 hand-picked cases and still claimed a span body could
not contain a dash - ``-b -p crit ... zu-`` disproves it, and only an
end-to-end sentence that happened to combine both shapes found it. Hence the
generator.
"""

import html
import json
import re
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "skills/jira-communication/scripts"))

from lib.markup import (  # noqa: E402
    escape_strikethrough,
    find_strikethrough_spans,
    lint_wiki_markup,
)

FIXTURES = Path(__file__).resolve().parent / "fixtures"
_ORACLE = json.loads((FIXTURES / "strikethrough_oracle.json").read_text(encoding="utf-8"))
_CORPUS = json.loads((FIXTURES / "strikethrough_corpus.json").read_text(encoding="utf-8"))

CASES = _ORACLE["cases"]
CORPUS_CASES = _CORPUS["cases"]
KNOWN_OVER = set(_CORPUS["known_over_predictions"])
KNOWN_UNDER = set(_CORPUS["known_under_predictions"])

_DEL_RE = re.compile(r"<del>(.*?)</del>", re.S)
# Mirrors lib.markup._split_verbatim; duplicated on purpose so a bug in that
# helper cannot hide itself by being used on both sides of the assertion.
_VERBATIM_RE = re.compile(r"^\s*\{(code|noformat)(?::[^}\n]*)?\}\s*$")


def _spans_in(markup: str) -> list[tuple[str, tuple[int, int]]]:
    """Every predicted span in ``markup``, as (line, span), skipping verbatim blocks."""
    found: list[tuple[str, tuple[int, int]]] = []
    open_tag = None
    for line in markup.split("\n"):
        match = _VERBATIM_RE.match(line)
        if open_tag is not None:
            if match is not None and match.group(1) == open_tag:
                open_tag = None
            continue
        if match is not None:
            open_tag = match.group(1)
            continue
        found += [(line, span) for span in find_strikethrough_spans(line)]
    return found


def _ids(cases):
    return [c["markup"] for c in cases]


class TestFixturesAreIntact:
    """Guards everything below: a truncated fixture makes every case vacuous."""

    def test_curated_oracle(self):
        assert len(CASES) >= 200
        assert any("<del>" in c["rendered"] for c in CASES)
        assert any("<del>" not in c["rendered"] for c in CASES)

    def test_generated_corpus(self):
        assert len(CORPUS_CASES) >= 5000
        struck = sum(1 for c in CORPUS_CASES if c["struck"])
        assert 100 <= struck <= len(CORPUS_CASES) - 100, f"corpus is one-sided: {struck} struck"


class TestNoFalseNegatives:
    """The load-bearing half: Jira struck it, so the model must have seen it."""

    @pytest.mark.parametrize("case", CORPUS_CASES, ids=_ids(CORPUS_CASES))
    def test_every_rendered_del_is_predicted(self, case):
        if not case["struck"]:
            return
        predicted = bool(_spans_in(case["markup"]))
        if case["markup"] in KNOWN_UNDER:
            assert not predicted, "known miss started passing - drop it from known_under_predictions"
            return
        assert predicted

    def test_known_misses_all_glue_two_regions_together(self):
        """The pinned misses must stay the shape they were accepted as.

        Every one writes a URL or link macro against another with at most a
        dash run between them, so Jira resolves the first and leaves the second
        literal. If a miss is ever added that does NOT look like that, this
        fails and the exemption has to be argued again.
        """
        for markup in KNOWN_UNDER:
            assert re.search(r"(\]|/[a-z0-9])\S{0,2}(\[|!|https?://)", markup), markup
        assert len(KNOWN_UNDER) <= 20


class TestOverPredictionsArePinned:
    """False positives are acceptable, but only the ones already accounted for."""

    @pytest.mark.parametrize("case", CORPUS_CASES, ids=_ids(CORPUS_CASES))
    def test_no_unexpected_over_prediction(self, case):
        if case["struck"] or not _spans_in(case["markup"]):
            return
        assert case["markup"] in KNOWN_OVER, (
            "new over-prediction; safe, but add it to known_over_predictions deliberately"
        )

    def test_the_documented_quirk_is_the_reason_for_most_of_them(self):
        # Jira abandons an opener whose body starts with one character followed
        # by a dash: `a -a-b- z` renders literally while `a -ab-cd- z` is
        # struck. Not modelled - the cost of predicting it is one redundant
        # escape, and a rule nobody can explain is a worse liability.
        assert find_strikethrough_spans("a -a-b- z")
        assert find_strikethrough_spans("a -ab-cd- z")


class TestAgainstCuratedOracle:
    @pytest.mark.parametrize("case", CASES, ids=_ids(CASES))
    def test_span_text_matches_rendered_del_body(self, case):
        spans = _spans_in(case["markup"])
        bodies = _DEL_RE.findall(case["rendered"])
        if len(spans) != len(bodies):
            # Covered by the corpus assertions above; the interesting check
            # here is the exact text, which only lines up one-to-one.
            return
        for (line, (opener, closer)), body in zip(spans, bodies, strict=True):
            if "<" in body:
                continue
            # Jira emits an escaped dash as &#45;, so compare against source.
            assert html.unescape(body) == line[opener + 1 : closer].replace("\\-", "-")

    @pytest.mark.parametrize("case", CASES, ids=_ids(CASES))
    def test_escaper_removes_every_span(self, case):
        assert _spans_in(escape_strikethrough(case["markup"])) == []


class TestEscaperClearsTheWholeCorpus:
    @pytest.mark.parametrize("case", CORPUS_CASES, ids=_ids(CORPUS_CASES))
    def test_no_span_survives_the_repair(self, case):
        assert _spans_in(escape_strikethrough(case["markup"])) == []


class TestRegressionsFromIssue226:
    """The shapes reported in netresearch/jira-skill#226, verbatim."""

    OPS_899 = (
        "Die nr-pforum-*Extensions waren als unabhängig dranstöpselbare "
        "Erweiterungen gedacht, jede für sich zu- und abschaltbar."
    )
    MONOSPACE = "Die {{nr-pforum-*}}-Extensions waren gedacht, jede für sich zu- und abschaltbar."

    def test_plain_prose_is_not_flagged(self):
        # Jira renders this one literally (recorded), so a finding here would be
        # the false positive that made the old lint unusable on German prose.
        assert find_strikethrough_spans(self.OPS_899) == []

    def test_monospace_boundary_opens_a_span(self):
        # `}}` is a non-word character, so the dash after it opens; `zu-` closes.
        assert len(find_strikethrough_spans(self.MONOSPACE)) == 1
        assert any("renders struck through" in f for f in lint_wiki_markup(self.MONOSPACE))

    def test_escaper_fixes_the_monospace_case(self):
        fixed = escape_strikethrough(self.MONOSPACE)
        assert fixed == "Die {{nr-pforum-*}}\\-Extensions waren gedacht, jede für sich zu- und abschaltbar."
        assert lint_wiki_markup(fixed) == []


class TestCliFlagsAlone:
    """A flag with no closer on the line is safe; with one, it is not.

    Both halves matter. Asserting only that flags are clean would be satisfied
    by a model that never reports anything.
    """

    @pytest.mark.parametrize(
        "text",
        [
            "journalctl -b -p crit zeigt die Fehler",
            "run -v then -x done",
            "run --v then --x done",
            "Ein Test mit --strict und danach noch -v am Ende",
            "start -word end -word2 tail",
            "offset by -5 seconds",
        ],
    )
    def test_no_closer_means_no_finding(self, text):
        assert find_strikethrough_spans(text) == []
        assert lint_wiki_markup(text) == []

    @pytest.mark.parametrize(
        "text",
        [
            "a paragraph with -v and a trailing word- here",
            "journalctl -b -p crit zeigt die Fehler; das Modul ist zu- und abschaltbar.",
        ],
    )
    def test_a_trailing_dash_later_on_the_line_does(self, text):
        assert find_strikethrough_spans(text)


class TestProtectedRegions:
    """A dash inside a link, URL or image is inert - escaping it breaks the link.

    This is the regression the whole masking layer exists for: GitLab merge
    request URLs carry a literal `/-/`, and this team pastes them into Jira
    comments constantly.
    """

    GITLAB = "[MR|https://git.netresearch.de/g/p/-/merge_requests/5] ist zu- und abschaltbar"

    def test_link_body_is_not_a_span(self):
        assert find_strikethrough_spans(self.GITLAB) == []

    def test_link_body_is_not_escaped(self):
        assert escape_strikethrough(self.GITLAB) == self.GITLAB

    def test_bare_url_is_protected(self):
        text = "Siehe https://x.de/a/-/b und das Modul zu- und abschaltbar"
        assert find_strikethrough_spans(text) == []
        assert escape_strikethrough(text) == text

    def test_image_macro_is_protected(self):
        assert find_strikethrough_spans("!-x.png! zu- foo") == []

    def test_dash_in_link_text_is_protected(self):
        assert find_strikethrough_spans("[Text mit -x|https://x.de] und zu- foo") == []

    def test_the_same_slash_dash_slash_in_prose_is_not(self):
        # Without the URL around it, `/-/` is an ordinary opener - measured.
        assert find_strikethrough_spans("a /-/ zu- b")

    def test_url_glued_to_a_word_is_not_autolinked_and_stays_live(self):
        # Jira does not autolink `ahttp://...`, so its dashes are prose.
        assert find_strikethrough_spans("x ahttp://x.de/a/-/b- y")

    def test_monospace_is_not_protected(self):
        # The one place the old implementation was right: text effects DO
        # apply inside {{...}}.
        assert find_strikethrough_spans("{{-x-}} y")
        assert find_strikethrough_spans("{{--strict}} foo bar- z")


class TestGrammarClauses:
    """One test per clause, so a regression names which rule broke."""

    def test_opener_needs_a_non_word_boundary(self):
        assert find_strikethrough_spans("word-x- y") == []
        assert find_strikethrough_spans("pre1-x- y") == []
        assert find_strikethrough_spans("a_-x- y") == [(2, 4)]

    def test_non_ascii_letters_are_word_characters(self):
        assert find_strikethrough_spans("Größe-x- y") == []
        assert find_strikethrough_spans("a -x-ä y") == []

    def test_closer_needs_a_non_space_before_it(self):
        assert find_strikethrough_spans("a -x - y") == []

    def test_closer_needs_a_non_word_after_it(self):
        assert find_strikethrough_spans("pre -x-y z") == []
        assert find_strikethrough_spans("pre -x- y") == [(4, 6)]

    def test_an_invalid_closer_is_skipped_not_fatal(self):
        # The defect the 168-case fixture missed: `-p` cannot close (space
        # before it), so the scan must carry on to `zu-` rather than give up.
        assert find_strikethrough_spans("a -b -p crit zu- z") == [(2, 15)]

    def test_escaped_dash_in_the_body_does_not_break_the_span(self):
        assert len(find_strikethrough_spans("a -x \\- y- b")) == 1

    def test_end_of_line_closes_a_span(self):
        assert find_strikethrough_spans("a -x-") == [(2, 4)]

    def test_in_a_run_the_last_dash_opens_and_the_first_closes(self):
        assert find_strikethrough_spans("a --foo-- b") == [(3, 7)]

    def test_escaped_dashes_are_literal(self):
        assert find_strikethrough_spans("a \\-x- b") == []

    def test_unicode_dashes_are_inert(self):
        assert find_strikethrough_spans("a –x– b") == []
        assert find_strikethrough_spans("a —x— b") == []


class TestEscaperMechanics:
    def test_whole_dash_run_is_escaped(self):
        # Escaping only the opener would promote the first dash of the run to
        # opener and leave the span alive - measured, see _escape_dash_run.
        assert escape_strikethrough("{{--strict}} foo bar- z") == "{{\\-\\-strict}} foo bar- z"

    def test_repeated_spans_all_get_fixed(self):
        assert escape_strikethrough("a -x- and -y- b") == "a \\-x- and \\-y- b"

    def test_clean_text_is_returned_unchanged(self):
        for case in CASES:
            if not _spans_in(case["markup"]):
                assert escape_strikethrough(case["markup"]) == case["markup"]

    def test_verbatim_blocks_are_left_alone(self):
        text = "{code}\na -x- b\n{code}"
        assert escape_strikethrough(text) == text

    def test_quote_and_panel_are_not_verbatim(self):
        # Jira parses text effects inside {quote}/{panel} (recorded), so the
        # escaper must reach into them.
        assert escape_strikethrough("{panel}\na {{m}}-x- b\n{panel}") == "{panel}\na {{m}}\\-x- b\n{panel}"


class TestEscaperTerminates:
    """The repair runs in the posting path; it must fail, never hang.

    Neutering _escape_dash_run during a mutation run hung the whole suite -
    the fixed-point loop had no progress guard. This pins the guard by making
    the repair a no-op and asserting the call still returns.
    """

    def test_a_non_progressing_repair_does_not_loop(self, monkeypatch):
        import lib.markup as markup

        monkeypatch.setattr(markup, "_escape_dash_run", lambda line, opener: line)
        text = "Die {{a}}-Extensions, jede zu- und abschaltbar"
        assert markup.escape_strikethrough(text) == text
        # The span survives, so the lint must still report it - a repair that
        # cannot converge has to stay visible, not be swallowed.
        assert any("renders struck through" in f for f in markup.lint_wiki_markup(text))


class TestCommentCliWiring:
    """The repair must be reachable from `jira-comment add`, not just importable."""

    @staticmethod
    def _repair_markup():
        import importlib.util

        path = Path(__file__).resolve().parents[1] / "skills/jira-communication/scripts/workflow/jira-comment.py"
        spec = importlib.util.spec_from_file_location("jira_comment_under_test", path)
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        return module._repair_markup

    def test_add_repairs_by_default(self):
        repair = self._repair_markup()
        assert repair("Die {{a}}-Extensions, jede zu- und abschaltbar", auto_escape=True) == (
            "Die {{a}}\\-Extensions, jede zu- und abschaltbar"
        )

    def test_no_auto_escape_leaves_the_text_alone(self):
        repair = self._repair_markup()
        text = "Die {{a}}-Extensions, jede zu- und abschaltbar"
        assert repair(text, auto_escape=False) == text

    def test_clean_text_is_untouched(self):
        repair = self._repair_markup()
        text = "journalctl -b -p crit zeigt die Fehler"
        assert repair(text, auto_escape=True) == text
